<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>file2prompt_logo.ico</ApplicationIcon>
	<Version>0.1.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="file2prompt_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\file2prompt\file2prompt.csproj" />
  </ItemGroup>
</Project>
